version: "3.8"
services:
  flask:
    build:
      context: ./todolist-flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
  node:
    build:
      context: ./todolist-vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - flask
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
